# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-20 21:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(help_text='Deja tu comentario', verbose_name='Comentario')),
            ],
        ),
        migrations.CreateModel(
            name='Prenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('tallas', models.CharField(blank=True, max_length=100, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('calificacion', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='comentario',
            name='receta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.Prenda'),
        ),
    ]
